<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Structly.AI.Hosting/Structly.AI.Hosting.csproj" />
    <ProjectReference Include="../../src/Structly.AI.Testing/Structly.AI.Testing.csproj" />
  </ItemGroup>
</Project>
